version: "3.5"

services: 
    postgres:
        restart: always
        container_name: db
        image: postgres:11.4
        ports:
            - "5432:5432"
        expose:
            - "5432"
        volumes:
            - local_postgres_data:/var/lib/postgresql/data
        networks:
            - net
volumes:
    local_postgres_data:
networks:
    net:
        driver: bridge
