version: "3.5"

services: 
    api:
        container_name: IHVolunteerAPI
        restart: always
        build:
            context: IHVolunteerAPI
        environment: 
            - CONNECTIONSTRINGS__APIDBCONTEXT=host=postgres;port=5432;database=postgres;username=shreyasdevalapurkar;
            - ASPNETCORE_URLS=http://+:5007
        ports:
            - "5007:5007"
        expose:
            - "5007"
        networks:
            - net
        depends_on:
            - postgres  
    postgres:
        restart: always
        container_name: db
        image: postgres:11.4
        ports:
            - "5432:5432"
        expose:
            - "5432"
        volumes:
            - local_postgres_data:/var/lib/postgresql/data
        networks:
            - net
volumes:
    local_postgres_data:
networks:
    net:
        driver: bridge
